name: Deploy to Clever Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Clever Cloud
        uses: 47ng/actions-clever-cloud@v2.0.0
        with:
          appID: ${{ secrets.CLEVER_APP_ID }}
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}

